### ISSUE TITLE
Validator stopped in block 515824 in mainnet

### ISSUE THREAD

**Issue by bitperfect-tleung** [ndau/commands#23]
Hi all,
I am facing an issue the validator stopped in block 515824 in mainnet. It seems there is an apphash issue. Is there any suggestion?

Thanks!

**Comment by edmcnierney** [comment]
We have seen this occur occasionally, and we're investigating. It happens when a node finds that +2/3rds votes are for a different apphash, so the block itself is valid and is added to the blockchain. The node with the problem, of course, doesn't think it is valid so it will not proceed. We do not yet have any information on the cause of the problem, but if you restart the node from the latest snapshot the problem should not occur. If you're running a standard Docker node, you can restart using the `./bin/removecontainer.sh` and `./bin/runcontainer.sh` scripts. Be sure to specify the same node identity file when you run the new container.

**Comment by edmcnierney** [comment]
Thanks - that's very helpful. We have also seen this symptom occasionally when restarting a node from a snapshot. In that case it always happens immediately after the snapshot. The current snapshot is 515,924 so 515,928 seems to be an instance of this problem.

Could you restart one more time doing the same thing and let me know the results? Thanks.

**Comment by edmcnierney** [comment]
Thanks for posting those logs. I'm going to try to reproduce from the same snapshot. There will also be a new snapshot available in about 40 minutes, so I'll let you know when you can try that one.

**Comment by edmcnierney** [comment]
There's a new snapshot from block 516,001, so if you restart again Docker will pull that one.

I just restarted three times from the snapshot you used and did not have a problem until the third time, when the node crashed but restarted automatically and continued. That is not surprising and there's nothing wrong with that snapshot. We think there may be something non-deterministic about recording node voting powers such that the same information is recorded in a different order, causing a mismatch. We're not sure about that yet. The fact that it failed twice for you is (I think) just bad luck. Thanks again for the help and for posting the log data.

**Comment by edmcnierney** [comment]
I have never seen this problem persist; in fact, it's been quite hard to reproduce. I don't have any other suggestions right now: could you tell the specs on the machine (AWS, I assume) you're running on?

**Comment by bitperfect-tleung** [comment]
I am running `Standard_D4_v4`(4vCPU and 16GB Ram) in Azure with Ubuntu 18.04. The instance works well for at least a month. This issue happened in these two days.

**Comment by bitperfect-tleung** [comment]
I have started the `t3.large` in AWS and it can catch up to the latest block now, thanks!
